on:
  workflow_dispatch:
    inputs:
      test:
        description: "testing workflow option"
        required: false
        default: "imnotsetbruv"
        type: string

jobs:
  lambda-run:
    runs-on: ubuntu-latest
    steps:
      - run: python lambda-code/main.py --string-input ${{inputs.test}}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          path: lambda-code/output.json