on:
  workflow_dispatch:
    branches:
      - "queue*"
    inputs:
      test:
        description: "testing workflow option"
        required: false
        default: "imnotsetbruv"
        type: string

jobs:
  lambda-queue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: pip install -r actions-tools/requirements.asc
      - run: python actions-tools/actions_queue.py
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          path: lambda-code/output.json